{
  "openapi": "3.1.1",
  "info": {
    "title": "AsyncJobScheduler.API | v1",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5121/"
    }
  ],
  "paths": {
    "/api/jobs": {
      "post": {
        "tags": [
          "AsyncJobScheduler.API"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateJobRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateJobRequest": {
        "type": "object",
        "properties": {
          "duration": {
            "pattern": "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$",
            "type": "string"
          },
          "shouldFail": {
            "type": "boolean"
          },
          "timeout": {
            "pattern": "^-?(\\d+\\.)?\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,7})?$",
            "type": [
              "null",
              "string"
            ]
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "AsyncJobScheduler.API"
    }
  ]
}